public with sharing class Constants {
  public final static String CREATED_MESSAGE_CODE = '20100';
  public final static String CREATED_MESSAGE_CONTENT = 'Create';
  public final static String OK_MESSAGE_CODE = '20000';
  public final static String OK_MESSAGE_CONTENT = 'Ok';
  //API CONSTANS BELOW
  public final static String API_CLIENT_ID = '{Your Client ID}';
  public final static String API_CLIENT_SECRET = '{Your Client Secret}';
  public final static String API_REFRESH_TOKEN = '{Your Refresh TOken}';
}
