public with sharing class Constants {
  public final static String CREATED_MESSAGE_CODE = '20100';
  public final static String CREATED_MESSAGE_CONTENT = 'Create';
  public final static String OK_MESSAGE_CODE = '20000';
  public final static String OK_MESSAGE_CONTENT = 'Ok';
  //API CONSTANS BELOW
  public final static String API_CLIENT_ID = '3MVG9fe4g9fhX0E7.ek7owrcpHzPSsyfqFgd6E8c2eIhSeFln61CcmEgL1YKynvVF3IcDT0m4M6WsK_rxsHUe';
  public final static String API_CLIENT_SECRET = '69A417AA0C167963A2E9262187DDDF371A9F306E73E04759E7E88AEE901A3F30';
  public final static String API_REFRESH_TOKEN = '5Aep861NGChdAifzi2NLkXB3pt_rO41rjrJtUS2GljYTT.1mrthonvJZRQRGIXbv9Vxtmr6lu5XHxCuKbpWWf.M';
}
